name: Deploy Azure Function (.NET 8 Isolated)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --output ./output

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: funclepatcore
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          app-name: 'funcleeplatcore'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

          
